kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kubernetes-deployment
  namespace: default
  labels:
    app: mysql-service
spec:
  replicas: 1
  selector:
     matchLabels:
        app: mysql-service
  template:
    metadata:
      labels:
        app: mysql-service
    spec:
      containers:
        - name: mysql-service-container
          image: church-rundown_mysql
          resources: {}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
